---
- name: Get repo from Zabbix Server role
  include_role:
    name: zabbix_server
    tasks_from: zabbix_repo.yml

- name: Packages installation
  apt:
    name: 'zabbix-agent'
    update_cache: yes

- name: Copy Zabbix Agent config
  template:
    src: "zabbix_agentd_01.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
    backup: yes
    mode: 0644
  notify:
    - zabbix agent restart
