---
- name: Flush old rules
  iptables:
    flush: true

#
# default policies
#
- name: Policy - Drop ipv6 connections
  iptables:
    chain: "{{ item }}"
    policy: DROP
    ip_version: ipv6
  with_items:
    "{{ iptables_chains_list }}"

- name: Policy - Drop ipv4 connections
  iptables:
    chain: "{{ item }}"
    policy: ACCEPT
  with_items:
    "{{ iptables_chains_list }}"

#
# INPUT chain
#
- name: INPUT chain - Allow established and related connections
  iptables:
    action: append
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: INPUT chain - Allow all loopback interface connections
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: INPUT chain - Allow common protocols
  iptables:
    action: append
    chain: INPUT
    source: 192.168.1.0/24
    protocol: tcp
    match: multiport
    destination_port: 22,10050:10051
    jump: ACCEPT
     
- name: INPUT chain - Allow ICMP
  iptables:
    action: append
    chain: INPUT
    protocol: icmp
    icmp_type: any
    jump: ACCEPT

- name: INPUT chain - Drop all INPUT
  iptables:
    action: append
    chain: INPUT
    jump: DROP

#
# OUTPUT chain
#
- name: OUTPUT chain - Allow established and related connections
  iptables:
    action: append
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: OUTPUT chain - Allow all OUTPUT loopback interface connections
  iptables:
    action: append
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT

- name: OUTPUT chain - Allow DNS and NTP by udp
  iptables:
    action: append
    chain: OUTPUT
    protocol: udp
    match: multiport
    destination_port: 53,123
    jump: ACCEPT

- name: OUTPUT chain - Allow DNS and NTP by tcp
  iptables:
    action: append
    chain: OUTPUT
    protocol: tcp
    match: multiport
    destination_port: 20,21,25,53,80,443
    jump: ACCEPT

- name: OUTPUT chain - Allow ICMP
  iptables:
    action: append
    chain: OUTPUT
    protocol: icmp
    icmp_type: any
    jump: ACCEPT

- name: OUTPUT chain - Drop all OUTPUT
  iptables:
    action: append
    chain: OUTPUT
    jump: DROP
