---
- name: Copy .bashrc
  copy:
    src: files/bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644

- name: Install packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - 'dnsutils'
    - 'curl'

- name: Upgrade all packages to the latest version
  apt: 
    upgrade: dist

#- name: Default iptables rules
#  include_role:
#    name: common
#    tasks_from: common_iptables.yml
