---
- name: MySQL installation
  include_role:
    name: mysql-server
    tasks_from: main.yml

- name: Copy .my.cnf for MySQL auth
  template:
    src: "my.cnf.j2"
    dest: "/root/.my.cnf"
    mode: 0600
    owner: root
    group: root

- name: Get Zabbix repo
  apt:
    deb: "{{ zbxs_repo_path }}"

- name: Packages installation
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - 'zabbix-server-mysql'
    - 'zabbix-frontend-php'
    - 'python-mysqldb'

- name: Check if DB zabbix exist
  shell: mysql -e 'show databases;' | grep zabbix
  register: dbexist
  failed_when: dbexist.rc == 2

- name: Unzip sql schema file
  shell: gunzip "{{ zbxs_mysql_schema_path }}/{{ zbxs_mysql_sql_file }}.gz"
  when: dbexist.rc == 1

- name: Correct sql schema files
  lineinfile:
    dest: "{{ zbxs_mysql_schema_path }}/{{ zbxs_mysql_sql_file }}"
    line: 'USE zabbix;'
  when: dbexist.rc == 1

- name: Create DB zabbix if not exist
  mysql_db:
    collation: utf8_bin
    encoding: utf8
    name: zabbix
    state: import
    target: "{{ zbxs_mysql_schema_path }}/{{ zbxs_mysql_sql_file }}"
  when: dbexist.rc == 1

- name: Create MySQL user and grant priveleges
  mysql_user:
    name: zabbix
    password: "{{ zbxs_mysql_zabbixdb_password }}"
    priv: 'zabbix.*:ALL'
  when: dbexist.rc == 1

# if you want to delete file with mysql root credentials from server uncomment this section
#- name: Delete .my.cnf
#  file:
#    path: "/root/.my.cnf"
#    state: absent

- name: Get current timezone
  shell: cat /etc/timezone
  register: timezone

- name: Prepare apache.conf
  replace:
    dest: /etc/zabbix/apache.conf
    regexp: '.*php_value date.timezone.*'
    replace: '        php_value date.timezone {{ timezone.stdout }}'

- name: Copy Zabbix server config
  template:
    src: "zabbix_server_01.conf.j2"
    dest: "/etc/zabbix/zabbix_server.conf"
    backup: yes
    mode: 0640
    owner: root
    group: zabbix
  tags: config
  notify:
    - zabbix server restart
    - apache2 restart

- name: Copy zabbix PHP config
  template:
    src: "zabbix.conf.php.j2"
    dest: "/etc/zabbix/web/zabbix.conf.php"
    backup: yes
    mode: 0640
    owner: www-data
    group: www-data
  notify:
    - zabbix server restart
    - apache2 restart
